services:
  backend:
    image: silas943245/backend:v1
    restart: always
    depends_on:
      - db
    deploy:
      replicas: 2
    expose:
      - 5000
    networks: 
      - application-network
      - db-network
    environment:
      FLASK_APP: "run.py"
      FLASK_DB_TYPE: "postgres"
      FLASK_DB_USER: "postgres"
      FLASK_DB_NAME: "postgres"
      FLASK_DB_PASSWORD: "secretpass"
      FLASK_DB_HOST: "db"
      FLASK_DB_PORT: "5432"

  frontend:
    image: silas943245/frontend:v1
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - application-network
    depends_on:
      - backend

  db:
    image: postgres:15.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: postgres
    container_name: db
    restart: always
    expose: 
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db-network

volumes:
  postgres_data:

networks:
  application-network:
  db-network:
