apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  FLASK_DB_TYPE: postgres
  FLASK_DB_USER: postgres
  FLASK_DB_NAME: postgres
  FLASK_DB_PASSWORD: secretpass
  FLASK_DB_HOST: db
  FLASK_DB_PORT: "5432"
